version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/backend/
    overwrite: true
hooks:
  ApplicationStart:
    - location: scripts/appstart.sh
      timeout: 300
      runas: root
 
