version: 0.2
env: 
  parameter-store: 
    MONGO: "/CodeBuild/mongo_yan"
phases:
  pre_build:
    commands:
       - npm install
  build:
    commands:
       - sed -i 's/localhost/'$MONGO'/' app.js

artifacts:
  files:
    - '**/*'
